version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: wc-interview-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

  # WordPress with WooCommerce
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wc-interview-wp
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 'true'
      WORDPRESS_DEBUG_LOG: 'true'
      WORDPRESS_DEBUG_DISPLAY: 'false'
    volumes:
      # Mount wp-content from repo
      - ./wp-content:/var/www/html/wp-content
      # Persist WordPress core
      - wordpress_data:/var/www/html
    networks:
      - wp-network

  # WP-CLI for automation
  wpcli:
    depends_on:
      - wordpress
      - db
    image: wordpress:cli
    container_name: wc-interview-cli
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp-network

volumes:
  db_data:
  wordpress_data:

networks:
  wp-network:
    driver: bridge
